# Generated by Django 2.2 on 2022-10-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senha',
            name='hora_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='senha',
            name='senha',
            field=models.IntegerField(),
        ),
    ]
